name: Frontend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  ACR_NAME: dimriresidentsregistry
  REGISTRY: dimriresidentsregistry.azurecr.io
  IMAGE_NAME: dimri-frontend
  RESOURCE_GROUP: rg-dimri-integrations
  CONTAINER_APP: dimri-frontend-container

 
  BACKEND_URL: https://dimri-backend-container.purpledune-c7fab2ea.westus2.azurecontainerapps.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. ACR Login
      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      # 4. Build Docker image (WITH BACKEND URL)
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=$BACKEND_URL \
            -t $REGISTRY/$IMAGE_NAME:latest \
            ./frontend

      # 5. Push image
      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest

      # 6. Deploy
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name $CONTAINER_APP \
            --resource-group $RESOURCE_GROUP \
            --image $REGISTRY/$IMAGE_NAME:latest